### ISSUE TITLE
Hacktoberfest Contributions

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/awesome-vulnerable#20]
Add any useful link with respect to pentesting and vulnerable machines.
Read [Guidelines](https://github.com/kaiiyer/awesome-vulnerable/blob/master/CONTRIBUTING.md) before making contribution!

**Comment by rohan2734** [comment]
hey can you elaborate the issue ,  i dont know about pentesting and vulnerable machines, and what do we need to know for that?

**Comment by kaiiyer** [comment]
Pentest, Vulnerability Assessment and bug bounty concepts are related to Red teaming activities in cyber security. The initial starter platforms to perform hacking and improve your skills are provided in the repo. 
Adding new platforms, vulnerable machines (docker images) and scripts can help the community explore the field.  If you know about any such resource feel free to make a PR. If you want to suggest a new feature then open an issue!

**Comment by rohan2734** [comment]
@kaiiyer  so is this related to hacking? and i need to add platforms related to that?

**Comment by kaiiyer** [comment]
> @kaiiyer  so is this related to hacking? and i need to add platforms related to that?

Yeah!

**Comment by rohan2734** [comment]
oh then i  give up here 😅.

**Comment by kaiiyer** [comment]
> oh then i give up here 😅.

Look for the fields you love!
Good luck
