### ISSUE TITLE
GitHub code or demo sites?

### ISSUE THREAD

**Issue by commjoen** [kaiiyer/awesome-vulnerable#36]
Dear @kaiiyer ,
Thank you for this awesome list! Sometimes the list refers to a demo site and sometimes to the GitHub code of a project. I have a few projects to add: OWASP webgoat8 an OWASP Wrongsecrets. Would you rather see links to GitHub code or to demo sites?

**Comment by kaiiyer** [comment]
Github code is preferred as default unless you really wanna show off the demo site.
